export const GET_USER = 'GET_USER';
export const GET_USER_REPOSITORIES = 'GET_USER_REPOSITORIES';
export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_REPOS_SUCCESS = 'FETCH_USER_REPOS_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const FETCH_USER_LOADING_END = 'FETCH_USER_LOADING_END';
