export const GET_USER = 'GET_USER';
export const GET_USER_REPOSITORIES = 'GET_USER_REPOSITORIES';
export const FETCH_USER_BEGIN = 'FETCH_USER_BEGIN';
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS';
export const FETCH_USER_REPOS_SUCCESS = 'FETCH_USER_REPOS_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const FETCH_USER_LOADING_END = 'FETCH_USER_LOADING_END';

export const UPLOAD_FILTER_REPOS_DATA = 'UPLOAD_FILTER_REPOS_DATA';
export const FILTER_ON_KEY_UP = 'FILTER_ON_KEY_UP';
export const SELECT_USER_REPO = 'SELECT_USER_REPO';
export const OPEN_SELECTED_REPOS = 'OPEN_SELECTED_REPOS';
export const HIDE_SELECTED_REPOS = 'HIDE_SELECTED_REPOS';
export const SHOW_ALL_REPOS = 'SHOW_ALL_REPOS';
export const HIDE_SINGLE_REPO = 'HIDE_SINGLE_REPO';
export const OPEN_SINGLE_REPO = 'OPEN_SINGLE_REPO';
export const SELECT_ALL_REPOS = 'SELECT_ALL_REPOS';
